export type Lang='en'|'ar'|'fr'|'es'|'de'|'tr'|'ja';
export const labels:Record<Lang,Record<string,string>>={
 en:{chat:'Chat',tools:'Tools',pricing:'Pricing',dashboard:'Dashboard',login:'Login',signup:'Create account',settings:'Settings',send:'Send',placeholder:'Message QLO 1.2...',welcome:'How can QLO help you today?',plan:'Current plan',usage:'AI usage',upgrade:'Upgrade',language:'Language',theme:'Theme'},
 ar:{chat:'الشات',tools:'الأدوات',pricing:'الأسعار',dashboard:'لوحة التحكم',login:'تسجيل الدخول',signup:'إنشاء حساب',settings:'الإعدادات',send:'إرسال',placeholder:'اكتب لـ QLO 1.2...',welcome:'إزاي QLO يساعدك النهارده؟',plan:'الخطة الحالية',usage:'استخدام الذكاء الاصطناعي',upgrade:'ترقية',language:'اللغة',theme:'المظهر'},
 fr:{chat:'Chat',tools:'Outils',pricing:'Tarifs',dashboard:'Tableau',login:'Connexion',signup:'Créer un compte',settings:'Réglages',send:'Envoyer',placeholder:'Message à QLO 1.2...',welcome:'Comment QLO peut-il aider ?',plan:'Forfait actuel',usage:'Usage IA',upgrade:'Améliorer',language:'Langue',theme:'Thème'},
 es:{chat:'Chat',tools:'Herramientas',pricing:'Precios',dashboard:'Panel',login:'Entrar',signup:'Crear cuenta',settings:'Ajustes',send:'Enviar',placeholder:'Mensaje a QLO 1.2...',welcome:'¿Cómo puede ayudar QLO?',plan:'Plan actual',usage:'Uso de IA',upgrade:'Mejorar',language:'Idioma',theme:'Tema'},
 de:{chat:'Chat',tools:'Tools',pricing:'Preise',dashboard:'Dashboard',login:'Login',signup:'Konto erstellen',settings:'Einstellungen',send:'Senden',placeholder:'Nachricht an QLO 1.2...',welcome:'Wie kann QLO helfen?',plan:'Aktueller Plan',usage:'KI-Nutzung',upgrade:'Upgrade',language:'Sprache',theme:'Design'},
 tr:{chat:'Sohbet',tools:'Araçlar',pricing:'Fiyatlar',dashboard:'Panel',login:'Giriş',signup:'Hesap oluştur',settings:'Ayarlar',send:'Gönder',placeholder:'QLO 1.2 mesajı...',welcome:'QLO bugün nasıl yardımcı olabilir?',plan:'Mevcut plan',usage:'AI kullanımı',upgrade:'Yükselt',language:'Dil',theme:'Tema'},
 ja:{chat:'チャット',tools:'ツール',pricing:'料金',dashboard:'ダッシュボード',login:'ログイン',signup:'アカウント作成',settings:'設定',send:'送信',placeholder:'QLO 1.2へメッセージ...',welcome:'QLOは何を手伝えますか？',plan:'現在のプラン',usage:'AI使用量',upgrade:'アップグレード',language:'言語',theme:'テーマ'}
};
